CREATE TABLE customer_shopping_data (
    customer_id INT,
    age INT,
    gender VARCHAR(50),
    item_purchased VARCHAR(100),
    category VARCHAR(100),
    purchase_amount NUMERIC,
    location VARCHAR(100),
    size VARCHAR(20),
    color VARCHAR(50),
    season VARCHAR(50),
    review_rating FLOAT,
    subscription_status VARCHAR(20),
    shipping_type VARCHAR(50),
    discount_applied VARCHAR(10),
    previous_purchases INT,
    payment_method VARCHAR(100),
    frequency_of_purchases VARCHAR(100),
    age_group VARCHAR(50),
    purchase_frequency_in_days FLOAT
);


Select* from customer_shopping_data

--Q1. What is the total revenue generated by the male and female customers?
Select gender, sum(purchase_amount) AS total_revenue
from customer_shopping_data
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
Select customer_id, purchase_amount
from customer_shopping_data
where discount_applied = 'Yes' and purchase_amount>=(select avg(purchase_amount) from customer_shopping_data)

--Q3 What are the top 5 products with the highest average rating review?
Select item_purchased, avg(review_rating) AS "top_5_highest_rating"
from customer_shopping_data
group by item_purchased
order by top_5_highest_rating DESC
limit 5

SELECT item_purchased, ROUND(AVG(review_rating:: numeric), 2) AS avg_rating
FROM customer_shopping_data
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;
