


Select* from customer_shopping_data

--Q1. What is the total revenue generated by the male and female customers?
Select gender, sum(purchase_amount) AS total_revenue
from customer_shopping_data
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
Select customer_id, purchase_amount
from customer_shopping_data
where discount_applied = 'Yes' and purchase_amount>=(select avg(purchase_amount) from customer_shopping_data)

--Q3 What are the top 5 products with the highest average rating review?
Select item_purchased, avg(review_rating) AS "top_5_highest_rating"
from customer_shopping_data
group by item_purchased
order by top_5_highest_rating DESC
limit 5

SELECT item_purchased, ROUND(AVG(review_rating:: numeric), 2) AS avg_rating
FROM customer_shopping_data
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

--Q4 Compare the average purchase amount between standard and express shipping.
Select shipping_type, round(avg(purchase_amount),2)
from customer_shopping_data
where shipping_type in('Express','Standard')
group by shipping_type

--Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
Select subscription_status, round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_shopping_data
group by subscription_status

--Q6 Which 5 products have highest percentage of products purchase with discount applied?
Select item_purchased,
round(100*(sum(case when discount_applied='Yes' then 1 else 0 end))/ count(*),2) as purchased_with_discount
from customer_shopping_data
group by item_purchased
order by purchased_with_discount desc
limit 5

--Q7 Segment customers into new, returning, and loyal customers based on their total number of previous purchase and show the count of each segment.
--Using CTEs(Common table expressions)
With customer_type as
(select customer_id, previous_purchases,
case 
   WHEN previous_purchases = 1 then 'New'
   WHEN previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer_shopping_data)

select customer_segment, count(*) as "Number_of_Customers"
from customer_type
group by customer_segment


--Q8 What are the top 3 most purchased products within each category?
With item_counts as (
select category, item_purchased, count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank 
from customer_shopping_data
group by category, item_purchased
)

Select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3

---Q9 Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
Select subscription_status, count(customer_id) as repeat_buyers
from customer_shopping_data
where previous_purchases > 5
group by subscription_status

--Q10 What is the revenue contributor of each age group?
Select age_group, sum(purchase_amount) as total_revenue
from customer_shopping_data
group by age_group
order by total_revenue desc




